# Generated by Django 2.1.5 on 2019-01-13 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editor.Author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Drawing'),
        ),
    ]
